lmcache_binary: lmcache
output_dir: outputs/replayer
l1_size_gb: 20
l1_init_size_gb: 20
eviction_policy: noop
l2_store_policy: skip_l1
l1_align_bytes: 4096
l2_type: fs_native
l2_base_path: /mnt/std-ssd/lmcache-trace-replay
l2_num_workers: 16
l2_extra:
  use_odirect: true
